upper bound pytest-html version <4.0.0
pytest-html 4.0.0 causes

  ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package

Could not yet find a public fix, therefore we temporary bound the
version